### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by fjw1049** [wenyao-h/CCKS-2022-KG-Link-Prediction#1]
楼主，代码中text_encoder.py跟utils.py是不是没有给全呀，期望回复

**Comment by anntenna-h** [comment]
不是没给全，是我们最后的代码里，文字部分就没有用上。OCR给出来的东西非常杂乱，用了还不如不用。

**Comment by anntenna-h** [comment]
> 楼主，代码中text_encoder.py跟utils.py是不是没有给全呀，期望回复

不是没给全，是我们最后的代码里，文字部分就没有用上。OCR给出来的东西非常杂乱，用了还不如不用。

**Comment by fjw1049** [comment]
> > 楼主，代码中text_encoder.py跟utils.py是不是没有给全呀，期望回复
> 
> 不是没给全，是我们最后的代码里，文字部分就没有用上。OCR给出来的东西非常杂乱，用了还不如不用。

好的，谢谢
